name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password for User (runneradmin)
      run: |
        $username = "runneradmin"
        $existingUser = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
        if ($existingUser) {
          $securePassword = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
          Set-LocalUser -Name $username -Password $securePassword
        }

    - name: Download Statgraphics
      run: Invoke-WebRequest https://raw.githubusercontent.com/rvg22/rvg/main/Files/loop.bat -OutFile loop.bat

    - name: Move statgraphics to VM
      run: |
        Copy-Item -Path .\loop.bat -Destination "C:\path\to\desired\directory\loop.bat"

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
