name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/rvg22/rvg/main/Files/NGROK-US.bat?token=GHSAT0AAAAAACIXFEBAURCNLOOPTWUVT3FKZJFWLGA -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/rvg22/rvg/main/Files/NGROK-CHECK.bat?token=GHSAT0AAAAAACIXFEBAEEQNWLPWRBX37U5IZJFWLXQ -OutFile NGROK-CHECK.bat
    - name: Make YML file for NGROK.

      run: start NGROK-US.bat
      
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password for User (runneradmin)
      run: |
        $username = "runneradmin"
        $existingUser = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
        if ($existingUser) {
          $securePassword = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
          Set-LocalUser -Name $username -Password $securePassword
        }

    - name: Download Statgraphics
      run: Invoke-WebRequest "https://402067.fs1.hubspotusercontent-na1.net/hubfs/402067/Downloads19-501/Statgraphics%20Centurion%2019%20Spanish%20X64.msi" -OutFile "Statgraphics_Centurion_19_Spanish_X64.msi"


    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Connect to your RDP 2core-7GB Ram.

      run: cmd /c NGROK-CHECK.bat
